services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: runway-fastapi
    container_name: runway-fastapi
    ports:
      - "8000:8000"
    env_file:
      - app\.env
    volumes:
      - ./app/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 